# Test profile
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  h2:
    console:
      enabled: false
  
  flyway:
    enabled: false

server:
  port: 0

cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
  allowed-headers: "*"
  allow-credentials: false

logging:
  level:
    root: WARN
    com.template.microservice: INFO
    org.hibernate.SQL: DEBUG