spring:
  application:
    name: gateway_service
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: events-service
              uri: http://localhost:8091
              predicates:
                - Path=/events/**
              filters:
                - StripPrefix=1

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info