name: CI/CD

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

permissions:
  contents: read
  pull-requests: write
  packages: write

jobs:
  pipeline:
    uses: hugobrun343/spring-boot-ci-cd-workflow/.github/workflows/spring-boot-pipeline.yml@v1.0.0
    with:
      cd-branches: '["main"]'
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}