name: CI/CD

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Spring Boot CI/CD
        uses: hugobrun343/template-spring-micro-service-CI@v2.0.0
        with:
          java-version: '21'
          cd-branches: '["main"]'
          github-token: ${{ secrets.GITHUB_TOKEN }}